CREATE TABLE Events (
	EventID INT PRIMARY KEY IDENTITY(1,1),
	EventName NVARCHAR(100) NOT NULL,
	EventDate DATETIME NOT NULL,
	Location NVARCHAR(255) NOT NULL,
	Description NVARCHAR(MAX) NULL
);

-- Primary key GUID - example using GUID
CREATE TABLE Invitations (
	InvitationID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	EventID INT NOT NULL,
	InviteeName NVARCHAR(100) NOT NULL,
	InviteeEmail NVARCHAR(255) NOT NULL,
	RSVPStatus NVARCHAR(50) NULL,
	CONSTRAINT FK_TableName_Events FOREIGN KEY (EventID) REFERENCES Events(EventID)
);

