<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pesutima.Domain\Pesutima.Domain.csproj" />
    <ProjectReference Include="..\Pesutima.Persistence\Pesutima.Persistence.csproj" />
  </ItemGroup>

</Project>
